/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Renewable Energy Forecast API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export interface Country {
    code: string;
    name: string;
    continent: string;
    flag?: string;
    /** @nullable */
    population?: number | null;
    /** @nullable */
    renewableSharePercent?: number | null;
    /** @nullable */
    totalCapacityGw?: number | null;
}
export interface CountryDetail {
    code: string;
    name: string;
    continent: string;
    flag?: string;
    /** @nullable */
    population?: number | null;
    /** @nullable */
    gdpBillionUsd?: number | null;
    /** @nullable */
    renewableSharePercent?: number | null;
    /** @nullable */
    totalCapacityGw?: number | null;
    /** @nullable */
    solarCapacityGw?: number | null;
    /** @nullable */
    windCapacityGw?: number | null;
    /** @nullable */
    hydroCapacityGw?: number | null;
    /** @nullable */
    biomassCapacityGw?: number | null;
    /** @nullable */
    geothermalCapacityGw?: number | null;
    /** @nullable */
    co2ReductionMtPerYear?: number | null;
    /** @nullable */
    policyTarget2030?: string | null;
}
export interface EnergyRecord {
    id: number;
    countryCode: string;
    countryName: string;
    /** solar | wind | hydro | biomass | geothermal | other */
    source: string;
    year: number;
    capacityGw: number;
    generationTwh: number;
    /** @nullable */
    percentOfTotal?: number | null;
}
export interface TrendPoint {
    year: number;
    totalCapacityGw: number;
    totalGenerationTwh: number;
    renewableSharePercent: number;
    /** @nullable */
    solarGw?: number | null;
    /** @nullable */
    windGw?: number | null;
    /** @nullable */
    hydroGw?: number | null;
    /** @nullable */
    biomassGw?: number | null;
    /** @nullable */
    geothermalGw?: number | null;
}
export interface CountryEnergyProfile {
    countryCode: string;
    countryName: string;
    records: EnergyRecord[];
    historicalTrend: TrendPoint[];
}
export interface ForecastPoint {
    year: number;
    source: string;
    projectedCapacityGw: number;
    projectedGenerationTwh: number;
    growthRatePercent: number;
    /** @nullable */
    confidenceLow?: number | null;
    /** @nullable */
    confidenceHigh?: number | null;
}
export interface GlobalStats {
    totalRenewableCapacityGw: number;
    totalRenewableGenerationTwh: number;
    renewableSharePercent: number;
    countriesTracked: number;
    yearOverYearGrowthPercent: number;
    co2AvoidedMt: number;
    topSolarCountry?: string;
    topWindCountry?: string;
    topHydroCountry?: string;
    fastestGrowingCountry?: string;
}
export interface CountryRanking {
    rank: number;
    countryCode: string;
    countryName: string;
    continent: string;
    flag?: string;
    value: number;
    unit: string;
    /** @nullable */
    changeFromLastYear?: number | null;
}
export interface SourceBreakdown {
    source: string;
    capacityGw: number;
    generationTwh: number;
    sharePercent: number;
    color: string;
    /** @nullable */
    yoyGrowthPercent?: number | null;
}
export interface PolicyAlert {
    id: number;
    countryCode: string;
    countryName: string;
    /** policy | milestone | investment | target | auction */
    category: string;
    headline: string;
    summary: string;
    /** @nullable */
    source?: string | null;
    /** @nullable */
    impactGw?: number | null;
    publishedAt: string;
}
export interface ContinentStat {
    continent: string;
    totalCapacityGw: number;
    renewableSharePercent: number;
    countryCount: number;
    leadingCountry: string;
    /** @nullable */
    solarGw?: number | null;
    /** @nullable */
    windGw?: number | null;
    /** @nullable */
    hydroGw?: number | null;
    /** @nullable */
    yoyGrowthPercent?: number | null;
}
export type ListCountriesParams = {
    continent?: string;
    search?: string;
};
export type ListEnergyDataParams = {
    countryCode?: string;
    source?: string;
    year?: number;
};
export type GetTopCountriesParams = {
    metric?: string;
    source?: string;
    limit?: number;
};
export type GetSourceBreakdownParams = {
    year?: number;
};
export type GetGlobalTrendsParams = {
    source?: string;
    fromYear?: number;
    toYear?: number;
};
export type ListAlertsParams = {
    countryCode?: string;
    category?: string;
    limit?: number;
};
//# sourceMappingURL=api.schemas.d.ts.map