/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Renewable Energy Forecast API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ContinentStat,
  Country,
  CountryDetail,
  CountryEnergyProfile,
  CountryRanking,
  EnergyRecord,
  ForecastPoint,
  GetGlobalTrendsParams,
  GetSourceBreakdownParams,
  GetTopCountriesParams,
  GlobalStats,
  HealthStatus,
  ListAlertsParams,
  ListCountriesParams,
  ListEnergyDataParams,
  PolicyAlert,
  SourceBreakdown,
  TrendPoint
} from './api.schemas';

import { customFetch } from '../custom-fetch';
import type { ErrorType } from '../custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * Returns server health status
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListCountriesUrl = (params?: ListCountriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/countries?${stringifiedParams}` : `/api/countries`
}

/**
 * @summary List all countries
 */
export const listCountries = async (params?: ListCountriesParams, options?: RequestInit): Promise<Country[]> => {

  return customFetch<Country[]>(getListCountriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListCountriesQueryKey = (params?: ListCountriesParams,) => {
    return [
    `/api/countries`, ...(params ? [params] : [])
    ] as const;
    }


export const getListCountriesQueryOptions = <TData = Awaited<ReturnType<typeof listCountries>>, TError = ErrorType<unknown>>(params?: ListCountriesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCountries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListCountriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listCountries>>> = ({ signal }) => listCountries(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listCountries>>, TError, TData> & { queryKey: QueryKey }
}

export type ListCountriesQueryResult = NonNullable<Awaited<ReturnType<typeof listCountries>>>
export type ListCountriesQueryError = ErrorType<unknown>


/**
 * @summary List all countries
 */

export function useListCountries<TData = Awaited<ReturnType<typeof listCountries>>, TError = ErrorType<unknown>>(
 params?: ListCountriesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listCountries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListCountriesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetCountryUrl = (code: string,) => {




  return `/api/countries/${code}`
}

/**
 * @summary Get country details
 */
export const getCountry = async (code: string, options?: RequestInit): Promise<CountryDetail> => {

  return customFetch<CountryDetail>(getGetCountryUrl(code),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCountryQueryKey = (code: string,) => {
    return [
    `/api/countries/${code}`
    ] as const;
    }


export const getGetCountryQueryOptions = <TData = Awaited<ReturnType<typeof getCountry>>, TError = ErrorType<void>>(code: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountry>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountryQueryKey(code);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountry>>> = ({ signal }) => getCountry(code, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(code), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountry>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountryQueryResult = NonNullable<Awaited<ReturnType<typeof getCountry>>>
export type GetCountryQueryError = ErrorType<void>


/**
 * @summary Get country details
 */

export function useGetCountry<TData = Awaited<ReturnType<typeof getCountry>>, TError = ErrorType<void>>(
 code: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountry>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCountryQueryOptions(code,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListEnergyDataUrl = (params?: ListEnergyDataParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/energy/data?${stringifiedParams}` : `/api/energy/data`
}

/**
 * @summary List energy data with filters
 */
export const listEnergyData = async (params?: ListEnergyDataParams, options?: RequestInit): Promise<EnergyRecord[]> => {

  return customFetch<EnergyRecord[]>(getListEnergyDataUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListEnergyDataQueryKey = (params?: ListEnergyDataParams,) => {
    return [
    `/api/energy/data`, ...(params ? [params] : [])
    ] as const;
    }


export const getListEnergyDataQueryOptions = <TData = Awaited<ReturnType<typeof listEnergyData>>, TError = ErrorType<unknown>>(params?: ListEnergyDataParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listEnergyData>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEnergyDataQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEnergyData>>> = ({ signal }) => listEnergyData(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEnergyData>>, TError, TData> & { queryKey: QueryKey }
}

export type ListEnergyDataQueryResult = NonNullable<Awaited<ReturnType<typeof listEnergyData>>>
export type ListEnergyDataQueryError = ErrorType<unknown>


/**
 * @summary List energy data with filters
 */

export function useListEnergyData<TData = Awaited<ReturnType<typeof listEnergyData>>, TError = ErrorType<unknown>>(
 params?: ListEnergyDataParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listEnergyData>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListEnergyDataQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetCountryEnergyDataUrl = (countryCode: string,) => {




  return `/api/energy/data/${countryCode}`
}

/**
 * @summary Get energy data for a specific country
 */
export const getCountryEnergyData = async (countryCode: string, options?: RequestInit): Promise<CountryEnergyProfile> => {

  return customFetch<CountryEnergyProfile>(getGetCountryEnergyDataUrl(countryCode),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCountryEnergyDataQueryKey = (countryCode: string,) => {
    return [
    `/api/energy/data/${countryCode}`
    ] as const;
    }


export const getGetCountryEnergyDataQueryOptions = <TData = Awaited<ReturnType<typeof getCountryEnergyData>>, TError = ErrorType<void>>(countryCode: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountryEnergyData>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountryEnergyDataQueryKey(countryCode);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountryEnergyData>>> = ({ signal }) => getCountryEnergyData(countryCode, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(countryCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountryEnergyData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountryEnergyDataQueryResult = NonNullable<Awaited<ReturnType<typeof getCountryEnergyData>>>
export type GetCountryEnergyDataQueryError = ErrorType<void>


/**
 * @summary Get energy data for a specific country
 */

export function useGetCountryEnergyData<TData = Awaited<ReturnType<typeof getCountryEnergyData>>, TError = ErrorType<void>>(
 countryCode: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountryEnergyData>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCountryEnergyDataQueryOptions(countryCode,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetCountryForecastUrl = (countryCode: string,) => {




  return `/api/energy/forecast/${countryCode}`
}

/**
 * @summary Get renewable energy forecast for a country
 */
export const getCountryForecast = async (countryCode: string, options?: RequestInit): Promise<ForecastPoint[]> => {

  return customFetch<ForecastPoint[]>(getGetCountryForecastUrl(countryCode),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCountryForecastQueryKey = (countryCode: string,) => {
    return [
    `/api/energy/forecast/${countryCode}`
    ] as const;
    }


export const getGetCountryForecastQueryOptions = <TData = Awaited<ReturnType<typeof getCountryForecast>>, TError = ErrorType<void>>(countryCode: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountryForecast>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountryForecastQueryKey(countryCode);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountryForecast>>> = ({ signal }) => getCountryForecast(countryCode, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(countryCode), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountryForecast>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCountryForecastQueryResult = NonNullable<Awaited<ReturnType<typeof getCountryForecast>>>
export type GetCountryForecastQueryError = ErrorType<void>


/**
 * @summary Get renewable energy forecast for a country
 */

export function useGetCountryForecast<TData = Awaited<ReturnType<typeof getCountryForecast>>, TError = ErrorType<void>>(
 countryCode: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCountryForecast>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCountryForecastQueryOptions(countryCode,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetGlobalStatsUrl = () => {




  return `/api/energy/global-stats`
}

/**
 * @summary Get global renewable energy statistics
 */
export const getGlobalStats = async ( options?: RequestInit): Promise<GlobalStats> => {

  return customFetch<GlobalStats>(getGetGlobalStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGlobalStatsQueryKey = () => {
    return [
    `/api/energy/global-stats`
    ] as const;
    }


export const getGetGlobalStatsQueryOptions = <TData = Awaited<ReturnType<typeof getGlobalStats>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getGlobalStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGlobalStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalStats>>> = ({ signal }) => getGlobalStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGlobalStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetGlobalStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getGlobalStats>>>
export type GetGlobalStatsQueryError = ErrorType<unknown>


/**
 * @summary Get global renewable energy statistics
 */

export function useGetGlobalStats<TData = Awaited<ReturnType<typeof getGlobalStats>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getGlobalStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetGlobalStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetTopCountriesUrl = (params?: GetTopCountriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/energy/top-countries?${stringifiedParams}` : `/api/energy/top-countries`
}

/**
 * @summary Get top countries by renewable capacity or generation
 */
export const getTopCountries = async (params?: GetTopCountriesParams, options?: RequestInit): Promise<CountryRanking[]> => {

  return customFetch<CountryRanking[]>(getGetTopCountriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTopCountriesQueryKey = (params?: GetTopCountriesParams,) => {
    return [
    `/api/energy/top-countries`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTopCountriesQueryOptions = <TData = Awaited<ReturnType<typeof getTopCountries>>, TError = ErrorType<unknown>>(params?: GetTopCountriesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTopCountries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTopCountriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTopCountries>>> = ({ signal }) => getTopCountries(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTopCountries>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTopCountriesQueryResult = NonNullable<Awaited<ReturnType<typeof getTopCountries>>>
export type GetTopCountriesQueryError = ErrorType<unknown>


/**
 * @summary Get top countries by renewable capacity or generation
 */

export function useGetTopCountries<TData = Awaited<ReturnType<typeof getTopCountries>>, TError = ErrorType<unknown>>(
 params?: GetTopCountriesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTopCountries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTopCountriesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetSourceBreakdownUrl = (params?: GetSourceBreakdownParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/energy/source-breakdown?${stringifiedParams}` : `/api/energy/source-breakdown`
}

/**
 * @summary Get global energy source breakdown
 */
export const getSourceBreakdown = async (params?: GetSourceBreakdownParams, options?: RequestInit): Promise<SourceBreakdown[]> => {

  return customFetch<SourceBreakdown[]>(getGetSourceBreakdownUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSourceBreakdownQueryKey = (params?: GetSourceBreakdownParams,) => {
    return [
    `/api/energy/source-breakdown`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetSourceBreakdownQueryOptions = <TData = Awaited<ReturnType<typeof getSourceBreakdown>>, TError = ErrorType<unknown>>(params?: GetSourceBreakdownParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSourceBreakdown>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSourceBreakdownQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSourceBreakdown>>> = ({ signal }) => getSourceBreakdown(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSourceBreakdown>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSourceBreakdownQueryResult = NonNullable<Awaited<ReturnType<typeof getSourceBreakdown>>>
export type GetSourceBreakdownQueryError = ErrorType<unknown>


/**
 * @summary Get global energy source breakdown
 */

export function useGetSourceBreakdown<TData = Awaited<ReturnType<typeof getSourceBreakdown>>, TError = ErrorType<unknown>>(
 params?: GetSourceBreakdownParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSourceBreakdown>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSourceBreakdownQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetGlobalTrendsUrl = (params?: GetGlobalTrendsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/energy/trends?${stringifiedParams}` : `/api/energy/trends`
}

/**
 * @summary Get global renewable energy trends over years
 */
export const getGlobalTrends = async (params?: GetGlobalTrendsParams, options?: RequestInit): Promise<TrendPoint[]> => {

  return customFetch<TrendPoint[]>(getGetGlobalTrendsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGlobalTrendsQueryKey = (params?: GetGlobalTrendsParams,) => {
    return [
    `/api/energy/trends`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetGlobalTrendsQueryOptions = <TData = Awaited<ReturnType<typeof getGlobalTrends>>, TError = ErrorType<unknown>>(params?: GetGlobalTrendsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getGlobalTrends>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGlobalTrendsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGlobalTrends>>> = ({ signal }) => getGlobalTrends(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGlobalTrends>>, TError, TData> & { queryKey: QueryKey }
}

export type GetGlobalTrendsQueryResult = NonNullable<Awaited<ReturnType<typeof getGlobalTrends>>>
export type GetGlobalTrendsQueryError = ErrorType<unknown>


/**
 * @summary Get global renewable energy trends over years
 */

export function useGetGlobalTrends<TData = Awaited<ReturnType<typeof getGlobalTrends>>, TError = ErrorType<unknown>>(
 params?: GetGlobalTrendsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getGlobalTrends>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetGlobalTrendsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListAlertsUrl = (params?: ListAlertsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/alerts?${stringifiedParams}` : `/api/alerts`
}

/**
 * @summary List policy and milestone alerts
 */
export const listAlerts = async (params?: ListAlertsParams, options?: RequestInit): Promise<PolicyAlert[]> => {

  return customFetch<PolicyAlert[]>(getListAlertsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListAlertsQueryKey = (params?: ListAlertsParams,) => {
    return [
    `/api/alerts`, ...(params ? [params] : [])
    ] as const;
    }


export const getListAlertsQueryOptions = <TData = Awaited<ReturnType<typeof listAlerts>>, TError = ErrorType<unknown>>(params?: ListAlertsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAlertsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAlerts>>> = ({ signal }) => listAlerts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData> & { queryKey: QueryKey }
}

export type ListAlertsQueryResult = NonNullable<Awaited<ReturnType<typeof listAlerts>>>
export type ListAlertsQueryError = ErrorType<unknown>


/**
 * @summary List policy and milestone alerts
 */

export function useListAlerts<TData = Awaited<ReturnType<typeof listAlerts>>, TError = ErrorType<unknown>>(
 params?: ListAlertsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listAlerts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListAlertsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetContinentStatsUrl = () => {




  return `/api/energy/continent-stats`
}

/**
 * @summary Get renewable energy stats grouped by continent
 */
export const getContinentStats = async ( options?: RequestInit): Promise<ContinentStat[]> => {

  return customFetch<ContinentStat[]>(getGetContinentStatsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetContinentStatsQueryKey = () => {
    return [
    `/api/energy/continent-stats`
    ] as const;
    }


export const getGetContinentStatsQueryOptions = <TData = Awaited<ReturnType<typeof getContinentStats>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getContinentStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetContinentStatsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getContinentStats>>> = ({ signal }) => getContinentStats({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getContinentStats>>, TError, TData> & { queryKey: QueryKey }
}

export type GetContinentStatsQueryResult = NonNullable<Awaited<ReturnType<typeof getContinentStats>>>
export type GetContinentStatsQueryError = ErrorType<unknown>


/**
 * @summary Get renewable energy stats grouped by continent
 */

export function useGetContinentStats<TData = Awaited<ReturnType<typeof getContinentStats>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getContinentStats>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetContinentStatsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







