import { z } from "zod/v4";
export declare const countriesTable: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "countries";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "countries";
            dataType: "number";
            columnType: "PgSerial";
            data: number;
            driverParam: number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        code: import("drizzle-orm/pg-core").PgColumn<{
            name: "code";
            tableName: "countries";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        name: import("drizzle-orm/pg-core").PgColumn<{
            name: "name";
            tableName: "countries";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        continent: import("drizzle-orm/pg-core").PgColumn<{
            name: "continent";
            tableName: "countries";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        flag: import("drizzle-orm/pg-core").PgColumn<{
            name: "flag";
            tableName: "countries";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        population: import("drizzle-orm/pg-core").PgColumn<{
            name: "population";
            tableName: "countries";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        gdpBillionUsd: import("drizzle-orm/pg-core").PgColumn<{
            name: "gdp_billion_usd";
            tableName: "countries";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        renewableSharePercent: import("drizzle-orm/pg-core").PgColumn<{
            name: "renewable_share_percent";
            tableName: "countries";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        totalCapacityGw: import("drizzle-orm/pg-core").PgColumn<{
            name: "total_capacity_gw";
            tableName: "countries";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        solarCapacityGw: import("drizzle-orm/pg-core").PgColumn<{
            name: "solar_capacity_gw";
            tableName: "countries";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        windCapacityGw: import("drizzle-orm/pg-core").PgColumn<{
            name: "wind_capacity_gw";
            tableName: "countries";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        hydroCapacityGw: import("drizzle-orm/pg-core").PgColumn<{
            name: "hydro_capacity_gw";
            tableName: "countries";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        biomassCapacityGw: import("drizzle-orm/pg-core").PgColumn<{
            name: "biomass_capacity_gw";
            tableName: "countries";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        geothermalCapacityGw: import("drizzle-orm/pg-core").PgColumn<{
            name: "geothermal_capacity_gw";
            tableName: "countries";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        co2ReductionMtPerYear: import("drizzle-orm/pg-core").PgColumn<{
            name: "co2_reduction_mt_per_year";
            tableName: "countries";
            dataType: "number";
            columnType: "PgReal";
            data: number;
            driverParam: string | number;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        policyTarget2030: import("drizzle-orm/pg-core").PgColumn<{
            name: "policy_target_2030";
            tableName: "countries";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const insertCountrySchema: z.ZodObject<{
    code: z.ZodString;
    name: z.ZodString;
    continent: z.ZodString;
    flag: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    population: z.ZodOptional<z.ZodNullable<z.ZodInt>>;
    gdpBillionUsd: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    renewableSharePercent: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    totalCapacityGw: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    solarCapacityGw: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    windCapacityGw: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    hydroCapacityGw: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    biomassCapacityGw: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    geothermalCapacityGw: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    co2ReductionMtPerYear: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    policyTarget2030: z.ZodOptional<z.ZodNullable<z.ZodString>>;
}, {
    out: {};
    in: {};
}>;
export type InsertCountry = z.infer<typeof insertCountrySchema>;
export type Country = typeof countriesTable.$inferSelect;
//# sourceMappingURL=countries.d.ts.map